[package]
name = "devsa/click-part-item-shop"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.14.1"
Roact = "roblox/roact@1.4.2"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"